spring.application.name=Expense-Tracker

#MySQL server Connection URL(expense_db)
spring.datasource.url=jdbc:mysql://localhost:3306/expense_db?useSSL=false&serverTimezone=UTC

#MySQL Username
spring.datasource.username=root

#MySQL Password(your_password_here)
spring.datasource.password=your_password_here

#MySQL Driver Class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate Configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#ddl-auto 'update
spring.jpa.hibernate.ddl-auto=update

#SQL Queries
spring.jpa.show-sql=true